/* Generated by brand/tools/build-brand.mjs - do not edit by hand.
   Geometry lives in brand/tools/geometry.mjs; run the script to regenerate. */

export const MONOGRAM_PATH = "M30 15 H42 V39 A10 10 0 0 1 22 39"
export const MONOGRAM_STROKE = 10
export const MONOGRAM_VIEWBOX = "0 0 64 64"
export const MONOGRAM_TIGHT_VIEWBOX = "17 10 30 44"

export const WORDMARK_PATHS: readonly string[] = ["M6 0 H22 V30 A10 10 0 0 1 2 30","M0 0 V28 A12 12 0 0 0 24 28 V0","M20 9.5 C20 4 16 -0.5 11 -0.5 C6 -0.5 2 4 2 9 C2 14 6 17 11 19 C16 21 20 25 20 30 C20 36 16 40.5 11 40.5 C6 40.5 2 36 2 30","M0 0 H24 M12 0 V40","M21 0 H0 V40 H21 M0 20 H16","M0 0 V40 M20 0 L1 21 M7 15 L22 40","M20 9.5 C20 4 16 -0.5 11 -0.5 C6 -0.5 2 4 2 9 C2 14 6 17 11 19 C16 21 20 25 20 30 C20 36 16 40.5 11 40.5 C6 40.5 2 36 2 30"]
export const WORDMARK_TRANSFORMS: readonly string[] = ["translate(-2 0)","translate(33 0)","translate(67 0)","translate(96 0)","translate(129 0)","translate(162 0)","translate(193 0)"]
export const WORDMARK_STROKE = 8
export const WORDMARK_VIEWBOX = "-4.5 -4.5 224 49"

export const LOCKUP_VIEWBOX = "0 -13 301.5 66"
export const LOCKUP_MONO_TRANSFORM = "translate(-25.5 -28) scale(1.5)"
export const LOCKUP_WORD_TRANSFORM = "translate(82.5 0)"
export const LOCKUP_RULE = {"x":61,"y":0,"w":1.5,"h":40} as const
