/**
 * Generate every brand asset from brand/tools/geometry.mjs.
 *
 * Run from the repo root:  node brand/tools/build-brand.mjs
 *
 * SVG output needs nothing but Node. The PNG icons and the social card need
 * `sharp`; if it is not installed the script writes the SVGs, reports what it
 * skipped and exits 0, so the vector system can always be regenerated.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MONO, WORD, lockup, monogramBounds, monogramPath, wordmark, round } from './geometry.mjs'
import {
  GOLD, INK, IVORY, faviconSvg, lockupSvg, monogramSvg,
  socialProfileSvg, wordmarkSvg,
} from './svg.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const pub = join(root, 'web', 'public')
const brand = join(pub, 'brand')
const written = []

async function put(path, contents) {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents)
  written.push(path.replace(root, '').replace(/\\/g, '/').replace(/^\//, ''))
}

/* ---- Vector marks ------------------------------------------------------ */

await put(join(brand, 'justeks-lockup.svg'), lockupSvg(INK, GOLD))
await put(join(brand, 'justeks-lockup-reverse.svg'), lockupSvg(IVORY, GOLD))
// Single-ink versions for embroidery, embossing and anything that cannot
// hold a second colour.
await put(join(brand, 'justeks-lockup-black.svg'), lockupSvg(INK, INK))
await put(join(brand, 'justeks-lockup-white.svg'), lockupSvg(IVORY, IVORY))
await put(join(brand, 'justeks-monogram.svg'), monogramSvg(INK))
await put(join(brand, 'justeks-monogram-reverse.svg'), monogramSvg(IVORY))
await put(join(brand, 'justeks-wordmark.svg'), wordmarkSvg(INK))
await put(join(brand, 'justeks-wordmark-reverse.svg'), wordmarkSvg(IVORY))
await put(join(brand, 'social-profile-dark.svg'), socialProfileSvg(INK, IVORY))
await put(join(brand, 'social-profile-light.svg'), socialProfileSvg(IVORY, INK))
await put(join(pub, 'favicon.svg'), faviconSvg())

/* ---- Path data for the React component --------------------------------- */

const { parts, width: wordW } = wordmark()
const mb = monogramBounds()
const l = lockup()
const half = WORD.stroke / 2 + 0.5

await put(join(root, 'web', 'src', 'components', 'brand', 'paths.ts'),
`/* Generated by brand/tools/build-brand.mjs - do not edit by hand.
   Geometry lives in brand/tools/geometry.mjs; run the script to regenerate. */

export const MONOGRAM_PATH = ${JSON.stringify(monogramPath())}
export const MONOGRAM_STROKE = ${MONO.stroke}
export const MONOGRAM_VIEWBOX = ${JSON.stringify(`0 0 ${MONO.box} ${MONO.box}`)}
export const MONOGRAM_TIGHT_VIEWBOX = ${JSON.stringify(
  `${mb.minX} ${mb.minY} ${round(mb.maxX - mb.minX)} ${round(mb.maxY - mb.minY)}`)}

export const WORDMARK_PATHS: readonly string[] = ${JSON.stringify(
  parts.map((p) => p.match(/d="([^"]+)"/)[1]))}
export const WORDMARK_TRANSFORMS: readonly string[] = ${JSON.stringify(
  parts.map((p) => p.match(/transform="([^"]+)"/)[1]))}
export const WORDMARK_STROKE = ${WORD.stroke}
export const WORDMARK_VIEWBOX = ${JSON.stringify(
  `${-half} ${-half} ${round(wordW + half * 2)} ${round(WORD.cap + half * 2)}`)}

export const LOCKUP_VIEWBOX = ${JSON.stringify(l.viewBox)}
export const LOCKUP_MONO_TRANSFORM = ${JSON.stringify(l.monoTransform)}
export const LOCKUP_WORD_TRANSFORM = ${JSON.stringify(l.wordTransform)}
export const LOCKUP_RULE = ${JSON.stringify(l.rule)} as const
`)

/* ---- Web app manifest --------------------------------------------------- */

await put(join(pub, 'site.webmanifest'), JSON.stringify({
  name: 'JUSTEKS',
  short_name: 'JUSTEKS',
  description: 'British-origin B2B textile supplier. Fabric, Perfected.',
  start_url: '/',
  display: 'standalone',
  background_color: '#FAF8F4',
  theme_color: '#FAF8F4',
  icons: [
    { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: '/brand/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
  ],
}, null, 2) + '\n')

/* ---- Raster icons and the social card ---------------------------------- */

let sharp
try { sharp = (await import('sharp')).default } catch { /* optional */ }

if (!sharp) {
  console.log(written.map((w) => `  ${w}`).join('\n'))
  console.log(`\n${written.length} vector files written.`)
  console.log('sharp not installed - skipped PNG icons and the social card.')
  process.exit(0)
}

/** Monogram on a solid square, sized so it keeps its clear space. */
function iconSvg(size, ground, colour, coverage) {
  const b = monogramBounds()
  const target = size * coverage
  const scale = target / Math.max(b.maxX - b.minX, b.maxY - b.minY)
  const w = (b.maxX - b.minX) * scale, h = (b.maxY - b.minY) * scale
  const dx = (size - w) / 2 - b.minX * scale
  const dy = (size - h) / 2 - b.minY * scale
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">`
    + `<rect width="${size}" height="${size}" fill="${ground}"/>`
    + `<g transform="translate(${round(dx)} ${round(dy)}) scale(${round(scale)})">`
    + `<path d="${monogramPath()}" fill="none" stroke="${colour}" stroke-width="${MONO.stroke}"`
    + ' stroke-linecap="butt" stroke-linejoin="miter"/></g></svg>'
}

const icons = [
  ['favicon-32.png', 32, 0.66],
  ['apple-touch-icon.png', 180, 0.56],
  ['icon-192.png', 192, 0.58],
  ['icon-512.png', 512, 0.58],
  // Maskable icons get cropped by some launchers, so the mark sits well
  // inside the safe zone.
  ['icon-512-maskable.png', 512, 0.42],
]

for (const [name, size, coverage] of icons) {
  const png = await sharp(Buffer.from(iconSvg(size, INK, IVORY, coverage)))
    .png({ compressionLevel: 9 }).toBuffer()
  await put(join(brand, name), png)
}

/* Social card: 1200x630, the box Open Graph and Twitter both crop from. */
const CARD_W = 1200, CARD_H = 630
const markW = 520
const markScale = markW / l.width
const markH = round(l.height * markScale)
const markX = round((CARD_W - markW) / 2)
const markY = 196

const card = `<svg xmlns="http://www.w3.org/2000/svg" width="${CARD_W}" height="${CARD_H}" viewBox="0 0 ${CARD_W} ${CARD_H}">
  <rect width="${CARD_W}" height="${CARD_H}" fill="${INK}"/>
  <g transform="translate(${markX} ${markY}) scale(${round(markScale)}) translate(0 ${-l.top})">
    <g fill="none" stroke="${IVORY}" stroke-width="${MONO.stroke}" stroke-linecap="butt" stroke-linejoin="miter">
      <path d="${monogramPath()}" transform="${l.monoTransform}"/>
    </g>
    <rect x="${l.rule.x}" y="${l.rule.y}" width="${l.rule.w}" height="${l.rule.h}" fill="#C8A96A"/>
    <g fill="none" stroke="${IVORY}" stroke-width="${WORD.stroke}" stroke-linecap="butt" stroke-linejoin="miter" transform="${l.wordTransform}">
      ${parts.join('')}
    </g>
  </g>
  <rect x="${markX}" y="${markY + markH + 44}" width="${markW}" height="1" fill="#C8A96A"/>
  <text x="${CARD_W / 2}" y="${markY + markH + 96}" text-anchor="middle"
        font-family="Helvetica, Arial, sans-serif" font-size="21" letter-spacing="5.5"
        fill="${IVORY}">BRITISH ORIGIN. GLOBAL REACH.</text>
  <text x="${CARD_W / 2}" y="${markY + markH + 140}" text-anchor="middle"
        font-family="Georgia, 'Times New Roman', serif" font-size="24" fill="#A79E92">Fabric, Perfected.</text>
</svg>`

await put(join(brand, 'og-default.png'),
  await sharp(Buffer.from(card)).png({ compressionLevel: 9 }).toBuffer())

console.log(written.map((w) => `  ${w}`).join('\n'))
console.log(`\n${written.length} files written.`)
