/**
 * Generate every brand asset from brand/tools/geometry.mjs.
 *
 * Run from the repo root:  node brand/tools/build-brand.mjs
 *
 * SVG output needs nothing but Node. The PNG icons and the social card need
 * `sharp`; if it is not installed the script writes the SVGs, reports what it
 * skipped and exits 0, so the vector system can always be regenerated.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { icon, lockup, monogram, round, stack, wordmark } from './geometry.mjs'
import {
  GOLD, INK, IVORY, faviconSvg, fills, iconSvg, lockupSvg,
  monogramSvg, stackSvg, wordmarkSvg,
} from './svg.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const pub = join(root, 'web', 'public')
const brand = join(pub, 'brand')
const written = []

async function put(path, contents) {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, contents)
  written.push(path.replace(root, '').replace(/\\/g, '/').replace(/^\//, ''))
}

/* ---- Vector marks ------------------------------------------------------ */

await put(join(brand, 'justeks-lockup.svg'), lockupSvg(INK, GOLD))
await put(join(brand, 'justeks-lockup-reverse.svg'), lockupSvg(IVORY, GOLD))
// Single-ink versions for embroidery, embossing and anything that cannot
// hold a second colour.
await put(join(brand, 'justeks-lockup-black.svg'), lockupSvg(INK, INK))
await put(join(brand, 'justeks-lockup-white.svg'), lockupSvg(IVORY, IVORY))
await put(join(brand, 'justeks-stack.svg'), stackSvg(INK, GOLD))
await put(join(brand, 'justeks-stack-reverse.svg'), stackSvg(IVORY, GOLD))
await put(join(brand, 'justeks-wordmark.svg'), wordmarkSvg(INK))
await put(join(brand, 'justeks-wordmark-reverse.svg'), wordmarkSvg(IVORY))
await put(join(brand, 'justeks-monogram.svg'), monogramSvg(INK))
await put(join(brand, 'justeks-monogram-reverse.svg'), monogramSvg(IVORY))
await put(join(brand, 'justeks-icon.svg'), iconSvg(INK))
await put(join(brand, 'justeks-icon-reverse.svg'), iconSvg(GOLD))
await put(join(brand, 'social-profile-dark.svg'), iconSvg(GOLD, INK))
await put(join(brand, 'social-profile-light.svg'), iconSvg(INK, IVORY))
await put(join(pub, 'favicon.svg'), faviconSvg())

/* ---- Path data for the React component --------------------------------- */

const w = wordmark()
const m = monogram()
const l = lockup()
const s = stack()
const ic = icon()

const box = (mark) => `0 ${mark.top} ${mark.width} ${round(mark.bottom - mark.top)}`

await put(join(root, 'web', 'src', 'components', 'brand', 'paths.ts'),
`/* Generated by brand/tools/build-brand.mjs - do not edit by hand.
   Geometry lives in brand/tools/geometry.mjs; run the script to regenerate. */

/** A glyph outline and the x it sits at. */
export interface MarkPart { readonly d: string; readonly x: number }

export const WORDMARK_PARTS: readonly MarkPart[] = ${JSON.stringify(w.parts)}
export const WORDMARK_VIEWBOX = ${JSON.stringify(box(w))}

export const MONOGRAM_PARTS: readonly MarkPart[] = ${JSON.stringify(m.parts)}
export const MONOGRAM_VIEWBOX = ${JSON.stringify(box(m))}

export const TAGLINE_PARTS: readonly MarkPart[] = ${JSON.stringify(l.tag.parts)}
export const TAGLINE_TRANSFORM = ${JSON.stringify(l.tagTransform)}

export const LOCKUP_VIEWBOX = ${JSON.stringify(l.viewBox)}
export const LOCKUP_RULE = ${JSON.stringify(l.rule)} as const

export const STACK_VIEWBOX = ${JSON.stringify(s.viewBox)}
export const STACK_MONO_TRANSFORM = ${JSON.stringify(s.monoTransform)}

export const ICON_VIEWBOX = ${JSON.stringify(`0 0 ${ic.size} ${ic.size}`)}
export const ICON_RING = ${JSON.stringify(ic.ring)} as const
export const ICON_TRANSFORM = ${JSON.stringify(ic.transform)}
`)

/* ---- Web app manifest --------------------------------------------------- */

await put(join(pub, 'site.webmanifest'), JSON.stringify({
  name: 'JUSTEKS',
  short_name: 'JUSTEKS',
  description: 'British-origin B2B textile supplier. Fabric, Perfected.',
  start_url: '/',
  display: 'standalone',
  background_color: IVORY,
  theme_color: IVORY,
  icons: [
    { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: '/brand/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
  ],
}, null, 2) + '\n')

/* ---- Raster icons and the social card ---------------------------------- */

let sharp
try { sharp = (await import('sharp')).default } catch { /* optional */ }

if (!sharp) {
  console.log(written.map((x) => `  ${x}`).join('\n'))
  console.log(`\n${written.length} vector files written.`)
  console.log('sharp not installed - skipped PNG icons and the social card.')
  process.exit(0)
}

/** A mark on a solid square, fitted by its ink to a share of the field. */
function squareSvg(mark, size, ground, colour, coverage) {
  const scale = (size * coverage) / Math.max(mark.width, mark.bottom - mark.top)
  const dx = (size - mark.width * scale) / 2
  const dy = (size - (mark.bottom - mark.top) * scale) / 2 - mark.top * scale
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">`
    + `<rect width="${size}" height="${size}" fill="${ground}"/>`
    + `<g transform="translate(${round(dx)} ${round(dy)}) scale(${round(scale)})">`
    + fills(mark.parts, colour) + '</g></svg>'
}

/** The ring mark on a solid square. */
function ringSquareSvg(size, ground, colour, coverage) {
  const inner = size * coverage
  const pad = round((size - inner) / 2)
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">`
    + `<rect width="${size}" height="${size}" fill="${ground}"/>`
    + `<g transform="translate(${pad} ${pad}) scale(${round(inner / ic.size)})">`
    + `<circle cx="${ic.ring.cx}" cy="${ic.ring.cy}" r="${ic.ring.r}" fill="none" `
    + `stroke="${colour}" stroke-width="${ic.ring.width}"/>`
    + `<g transform="${ic.transform}">${fills(ic.parts, colour)}</g></g></svg>`
}

// The 32px favicon drops the ring: at that size it closes up into a blob and
// takes the letters with it. Everything larger keeps the full icon.
const icons = [
  ['favicon-32.png', () => squareSvg(m, 32, INK, IVORY, 0.62)],
  ['apple-touch-icon.png', () => ringSquareSvg(180, INK, GOLD, 0.86)],
  ['icon-192.png', () => ringSquareSvg(192, INK, GOLD, 0.86)],
  ['icon-512.png', () => ringSquareSvg(512, INK, GOLD, 0.86)],
  // Maskable icons get cropped by some launchers, so the mark sits well
  // inside the safe zone.
  ['icon-512-maskable.png', () => squareSvg(m, 512, INK, GOLD, 0.4)],
]

for (const [name, build] of icons) {
  await put(join(brand, name),
    await sharp(Buffer.from(build())).png({ compressionLevel: 9 }).toBuffer())
}

/* Social card: 1200x630, the box Open Graph and Twitter both crop from.
   Drawn entirely from outlines, so it renders identically everywhere and
   never depends on a font being installed on the machine building it. */
const CARD_W = 1200
const CARD_H = 630
const markW = 560
const markScale = round(markW / s.width)
const markY = round((CARD_H - (s.bottom - s.top) * markScale) / 2 - s.top * markScale)

const card = `<svg xmlns="http://www.w3.org/2000/svg" width="${CARD_W}" height="${CARD_H}" viewBox="0 0 ${CARD_W} ${CARD_H}">
  <rect width="${CARD_W}" height="${CARD_H}" fill="${INK}"/>
  <g transform="translate(${round((CARD_W - markW) / 2)} ${markY}) scale(${markScale})">
    ${fills(s.word.parts, IVORY)}
    <rect x="${s.rule.x}" y="${s.rule.y}" width="${s.rule.w}" height="${s.rule.h}" fill="${GOLD}"/>
    <g transform="${s.tagTransform}">${fills(s.tag.parts, GOLD)}</g>
    <g transform="${s.monoTransform}">${fills(s.mono.parts, IVORY)}</g>
  </g>
</svg>`

await put(join(brand, 'og-default.png'),
  await sharp(Buffer.from(card)).png({ compressionLevel: 9 }).toBuffer())

console.log(written.map((x) => `  ${x}`).join('\n'))
console.log(`\n${written.length} files written.`)
